# Generated by Django 4.1.3 on 2022-12-08 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pmapp', '0002_alter_appuser_email_portfolio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='currentPrice',
            new_name='currentprice',
        ),
    ]
