# Generated by Django 4.1.3 on 2022-12-08 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmapp', '0004_remove_portfolio_marketvalue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='currentprice',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='totalcost',
            field=models.FloatField(null=True),
        ),
    ]
