# Generated by Django 4.1.3 on 2022-12-10 16:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pmapp', '0010_alter_portfolio_owner_alter_wallet_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='amount',
            field=models.FloatField(default=100000),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Wallet',
        ),
    ]
