# Generated by Django 4.1.3 on 2022-12-10 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmapp', '0012_remove_appuser_amount_wallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='totalfund',
            field=models.FloatField(default=100000.0),
        ),
    ]
