# Generated by Django 4.1.3 on 2022-12-12 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmapp', '0013_alter_wallet_totalfund'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='totalfund',
        ),
        migrations.AlterField(
            model_name='wallet',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=100000.0, max_digits=254),
        ),
    ]
