# Generated by Django 4.1.3 on 2022-12-12 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmapp', '0014_remove_wallet_totalfund_alter_wallet_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='buyprice',
            field=models.DecimalField(decimal_places=4, max_digits=254),
        ),
    ]
