# Generated by Django 4.1.3 on 2022-12-14 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmapp', '0017_wallet_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='total',
            field=models.FloatField(default=0),
        ),
    ]
