# Generated by Django 4.1.3 on 2022-12-14 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pmapp', '0018_alter_wallet_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='total',
        ),
    ]
